### ISSUE TITLE
What is the puzzle input?

### ISSUE THREAD

**Issue by tommercutio** [karasek/CrossWord#1]
Hi,

Good job with the library. I like the algorithm you've implemented. I'm trying to make it work without any success.

In Program.cs in the main project, your program expects 4 inputs in the args.

`out inputFile, out outputFile, out puzzle, out dictionaryFile`

The input file is the board template like the sample templates you've generated. The dictionary is the list of words and the output file is the file the program writes the result to.

I can't figure out what the puzzle argument should be and how it should be formatted.

Any help is appreciated. Thanks.

**Comment by karasek** [comment]
Hi, for example:

CrossWord -i "c:\projects\CrossWord\templates\template1.txt" -o "out.txt" -d "c:\projects\CrossWord\dict\en" -p "TEST"

gives out.txt:

```
00: - - D I A 
01: - T E S T 
02: C H I L E 
03: R A S E - 
04: T I T - - 

Patterns: 
-,2,0,DIA,defense intelligence agency
-,1,1,TEST,essay
-,0,2,CHILE,Republic of Chile
-,0,3,RASE,dismantle
-,0,4,TIT,boob
|,0,2,CRT,cathode-ray tube
|,1,1,THAI,central thai
|,2,0,DEIST,deistic
|,3,0,ISLE,islet
|,4,0,ATE,Greek deity (generic term)
```

puzzle should be without spaces

**Comment by tommercutio** [comment]
Thank you.

I'm not sure I understand, bear with me.

In your example, how does the program use the "TEST" argument?

**Comment by karasek** [comment]
PuzzlePlacer class tries `GetAllPossiblePlacements` positions of puzzle, for example for 'LONGERTEST' one might be:

```
00: - - . L E 
01: - . . O S 
02: . . . N T 
03: . . . G - 
04: E R T - - 
```

and try to finish filling, for example:

```
00: - - S L E 
01: - A M O S 
02: S C A N T 
03: B E R G - 
04: E R T - - 
```

**Comment by tommercutio** [comment]
So it's like a theme for the board. It will always place the puzzle on the board and then fill the spaces.

How can I make it start empty and fill all the positions with only words from the dictionary?

**Comment by karasek** [comment]
I've made --puzzle parameter optional #fb73d1301faed936bb028eceaa433c3862c0f9cc
