### ISSUE TITLE
How to generate all possible puzzles

### ISSUE THREAD

**Issue by tommercutio** [karasek/CrossWord#2]
Given a dictionary and a board, how can I make the code find all unique combinations?

Right now, I'm trying to do this by shuffling the words. But I wanted to ask if there is an already coded way to achieve this via the library.

**Comment by karasek** [comment]
Variation with user defined puzzle tries all possible placements of puzzle and then generate rest - you can get multiple solution by simple not cancelling other generating threads when first solution is found. Otherwise generating board without puzzle finds only one solution and slight modification of Generate function would be needed.

**Comment by tommercutio** [comment]
I tried tracing the code to accomplish this but so far no luck. Could you help me with this?

In fact, if it's not too much to ask and if it's a small enough task, I'd appreciate if you could implement this.

**Comment by karasek** [comment]
No problem, I will extend next week after finishing product release at my day job.

**Comment by tommercutio** [comment]
I would really appreciate this. Thank you.

**Comment by karasek** [comment]
Implemented, see the commit, during a while it spitted out tons of solutions for a small board and still continues :-)

```
Solution 0 found:
00: - - - B A N - - - 
01: - - S A H I B - - 
02: - S E N A T E S - 
03: S E T S - S T E P 
04: O R T - - - T A - 
05: B A L L - S I R S 
06: - L E A S H E S - 
07: - - S I T U S - - 
08: - - - C U T - - -
```

```
Solution 10347233 found:
00: - - - B A N - - - 
01: - - S A H I B - - 
02: - S E N A T E S - 
03: D I M S - S T E P 
04: A N I - - - T A - 
05: N U N S - S I R S 
06: - S A L V O E S - 
07: - - L O A D S - - 
08: - - - B R A - - -  
```
